let nome = prompt("Digite seu nome")
let nascimento = prompt("Digite sua data de nascimento'Utilize /'")
let endereco = prompt("Digite seu endereço")
let cpf = prompt("Digite seu CPF")
let esco = prompt("Digite sua escolaridade")
let cnh = confirm("Possui CNH ?")
let filhos = Number(prompt("Quantos filhos possui?"))
let cargo = prompt("Qual seu cargo atual ?")
let salario = Number(prompt("Qual seu salario atual?"))
let comissao = confirm("Recebe comissão? Se sim, aperte em confirme, caso não, clique em cancel")
let adm = Number(prompt("Informe o ano de admissão"))

console.log("Nome do candidato:", nome)
console.log("Data de nascimento:", nascimento)
console.log("Endereço:", endereco )
console.log("CPF:", cpf)
console.log("Escolaridade:", esco)
console.log("Possui CNH - ", cnh)
console.log("Numero de filhos:", filhos)
console.log("Cargo atual:", cargo)
console.log("Salario atual:", salario)
console.log("Recebe comissão:", comissao)
console.log("Ano de admissão:", adm)

